### PR TITLE
Updated settings file to automatically indent cursor via given regex...

### PR DESCRIPTION
**Pull request by colbyn**

### CODE REVIEW

**Comment by nwolverson** [comment]
Anyone have an opinion on this?

**Comment by MiracleBlue** [comment]
I think this is definitely something we should add!

My only concern is that the list of keywords is hard-coded there.  Would be kinda nice to have some reference-able store of reserved keywords and symbols that can be used with this as well, but with regexes, I imagine this could potentially be more trouble than its worth.

Otherwise, can we add the assignment operator (`=`) to this?

Good stuff @colbyn :)

**Comment by MiracleBlue** [comment]
Oh wait, I think you already have the `=` operator there!

If so, I say we go ahead and merge :)

**Comment by colbyn** [comment]
Oh, perhaps I should acknowledge that this snippet is stolen from the [language Haskell package](https://github.com/atom-haskell/language-haskell/blob/master/settings/language-haskell.cson#L4) (something I didn’t think to mention). 

Furthermore, it just occurred to me that the ‘where’ pattern will apply to module declarations, as well as the intended where expression binders.

For me I’ve become accustomed to such when adding new modules, given I prefer my cursor to auto indent following a where expression binder. Although this may upset your current user base if they are not accustomed to such. 


Anyway, just trying to help, and thought I should let you know about the aforementioned behavior, if you didn’t already.

**Pull request merged**
