### PR TITLE
Grammar update 2 fix1

### PR DESCRIPTION
**Pull request by wclr**
Fix for issue in https://github.com/purescript-contrib/atom-language-purescript/pull/56 with `px = Proxy :: Proxy "fdsfsdf"`

image

### CODE REVIEW

**Comment by wclr** [comment]
Oh this git, I wonder why it shows the conflict.

**Comment by mikesol** [comment]
I'll use this for a week-ish and report back if I see anything wrong. Ping me if you don't hear from me!

**Comment by mikesol** [comment]
Also confirming that the file in question is now correctly highlighted.
Screen Shot 2022-08-16 at 6 28 14 AM

**Comment by nwolverson** [comment]
Going to merge this right away since the version on master is known to be broken, but not push a release immediately.

@wclr if you have any further refinements / issues noticed can you start from master

**Comment by mikesol** [comment]
It looks like there's still a tiny bug. This use of triple-quotes is likely mega-super-rare, though.
Screen Shot 2022-08-22 at 9 57 44 AM
.

**Comment by nwolverson** [comment]
@mikesol is that triple quotes only being an issue for type level strings?

**Comment by mikesol** [comment]
> @mikesol is that triple quotes only being an issue for type level strings?

yup, only type-level strings.
here's the term-level working correctly:
Screen Shot 2022-08-22 at 12 29 03 PM

**Comment by wclr** [comment]
Have fixed it in https://github.com/purescript-contrib/atom-language-purescript/pull/60

**Pull request merged**
