### PR TITLE
Remove language-haskell dependency

### LINKED ISSUE #6: undocumented pre-requisite: language-haskell
I get this message after installing `language-purescript` `0.4.0`:

screen shot 2015-09-05 at 6 16 25 pm

Should this be defined as a specific dependency? Everything seems to work after installing the latest version of `language-haskell`.

### PR DESCRIPTION
**Pull request by nwolverson**
I think @hdgarrood removed the dependency on `language-haskell` but there is still startup code to check that it is there. This removes the related code. Should fix #6. 

Also @freebroccolo would be good to get a release, I notice that I've been using a local version with @hdgarrood's changes for months and didn't realise that it is never released.

(I'm not sure I understand why the generated grammar is checked in but in `.gitignore`?)

### CODE REVIEW

**Comment by freebroccolo** [comment]
Thanks, I will take a look at it. Unfortunately I haven't been using Atom for awhile now and haven't used purescript all that much recently either so this package is not very well maintained. If you are interested in taking over or know someone else who is I'd be happy to add them to the repo or transfer it. /cc @paf31

**Comment by paf31** [comment]
If you'd like us to manage PRs, reviews etc., we could maybe move this into `purescript-contrib`?

**Comment by freebroccolo** [comment]
@paf31 that sounds good to me. I apparently don't have the ability to initiate a transfer to `purescript-contrib` but I think I can transfer to you and let you do it.

**Comment by paf31** [comment]
@freebroccolo Sounds good, will do, thanks!

**Comment by paf31** [comment]
I'm happy to act as maintainer if necessary, but @nwolverson, if you're interested, please let me know and I'll set up the permissions appropriately.

**Comment by nwolverson** [comment]
Yup happy to help. Still would be good to get input from @hdgarrood who did a bunch of work on this.

**Comment by hdgarrood** [comment]
Input on what, sorry? The PR looks good to me. I don't use Atom, though, so I don't think I'd be able to do a very good job as a maintainer apart from on the grammar part (the aim of my work there was to improve PureScript syntax highlighting on GitHub).

**Comment by nwolverson** [comment]
@hdgarrood Specifically on the PR, since you committed the changes to add the actual grammar (grammars/purescript.cson) to `.gitignore` yet updated the grammar in the repository, I wondered if I misunderstood the build process. I understand that this might just have been copied verbatim from the haskell version. My understanding is it's a manual script which generates the grammar and the grammar should be checked in (rather than somehow being generated on package install).

Oh on top of that, you mentioned something about possible improvements to the grammar, if there are any that you know of & aren't already in the TODO would be good to note those down.

Again I do use Atom and maintain the other package, so happy to take this on.

**Comment by hdgarrood** [comment]
Ah, right. Yes. I think I might have checked it in for github highlighting. Perhaps it should be removed from gitignore.

I'm sorry, I don't remember any of the ways this grammar could be improved. There were definitely a couple, and I had a look, but I don't think I wrote them down anywhere. I remember thinking that trying to get it 100% accurate is probably impossible given that we only have regexes as opposed to an actual parser, though.

**Comment by hdgarrood** [comment]
Oh, looks like I checked in a file `todo.txt` with ways the grammar could be improved.

**Pull request merged**
